spring:
  datasource:
    url: jdbc:mysql://localhost:13306/eventmesh?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: sodafang
    password: asdfasdf
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
event-mesh:
  admin-server:
    port: 8081